### ISSUE TITLE
Laravel 5.1

### ISSUE THREAD

**Issue by coolynx** [Hedronium/SpacelessBlade-Legacy#1]
Looks like in Laravel 5.1 BladeCompiler.php has been rewritten and SpacelessBlade no more works.

**Comment by omranjamal** [comment]
Sorry for the very late reply. This repo is no longer maintained. Please use [hedronium/spacelessblade](https://github.com/Hedronium/SpacelessBlade).

We had this little name and with that namespace change in the middle.
